<?php

namespace BackendBundle\Repository;

/**
 * EpidodePeopleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpidodePeopleRepository extends \Doctrine\ORM\EntityRepository
{
}
